vim.keymap.set("n", "<leader>aa", ":ArduinoAttach<CR>a")
vim.keymap.set("n", "<leader>av", ":ArduinoVerify<CR>a")
vim.keymap.set("n", "<leader>au", ":ArduinoUpload<CR>a")
vim.keymap.set("n", "<leader>aus", ":ArduinoUploadAndSerial<CR>a")
vim.keymap.set("n", "<leader>as", ":ArduinoSerial<CR>a")
vim.keymap.set("n", "<leader>ab", ":ArduinoChooseBoard<CR>a")
vim.keymap.set("n", "<leader>ap", ":ArduinoChooseProgrammer<CR>a")
